

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: expenses
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: expense_backend
    ports:
      - '5000:5000'
    depends_on:
      - db
    volumes:
      - ./backend:/app

volumes:
  pgdata:

